ALTER TABLE question MODIFY like_count INT(11) NOT NULL DEFAULT '0';
ALTER TABLE question MODIFY view_count INT(11) NOT NULL DEFAULT '0';
ALTER TABLE question MODIFY comment_count INT(11) NOT NULL DEFAULT '0';